import AuthProvider from "@/context/AuthProvider";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navbar/Navbar";
import { CurrentTabProvider } from "@/context/CurrentTabContext";
import "./globals.css";
import "react-quill/dist/quill.snow.css";

export const metadata = {
  title: "MS Outlook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CurrentTabProvider>
            <Toaster />
            <Navbar />
            {children}
          </CurrentTabProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
